"""Markdown reports in docs/: results, use-case backlog and AI evaluation."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from .generate import DIGITAL_INTAKE_LAUNCH
from .kpis import KPIS, _joined, compute_kpis, format_value, kpis_by
from .model import SLA_ARRIVAL_MIN, StarSchema
from .quality import QualityResult


def _table(df: pd.DataFrame) -> str:
    header = "| " + " | ".join(str(c) for c in df.columns) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep, *body])


def insights(star: StarSchema) -> dict[str, float | str]:
    """The findings the report states, computed from the data rather than written by hand."""
    j = _joined(star)
    road = j[j["service_group"] == "Road"]
    winter = road["season"] == "Winter"
    before = pd.to_datetime(j["created_at"]) < DIGITAL_INTAKE_LAUNCH
    region = kpis_by(star, "region").sort_values("sla_compliance_rate")
    answered = road[road["csat"].notna()]
    return {
        "sla_winter": float(road.loc[winter, "sla_met"].mean()),
        "sla_rest": float(road.loc[~winter, "sla_met"].mean()),
        "arrival_winter": float(road.loc[winter, "arrival_min"].median()),
        "arrival_rest": float(road.loc[~winter, "arrival_min"].median()),
        "app_before": float((j.loc[before, "channel"] == "App").mean()),
        "app_after": float((j.loc[~before, "channel"] == "App").mean()),
        "app_contact_before": float(j.loc[before & (j["channel"] == "App"), "first_contact_min"].mean()),
        "app_contact_after": float(j.loc[~before & (j["channel"] == "App"), "first_contact_min"].mean()),
        "weakest_region": str(region.iloc[0]["region"]),
        "weakest_region_sla": float(region.iloc[0]["sla_compliance_rate"]),
        "strongest_region": str(region.iloc[-1]["region"]),
        "strongest_region_sla": float(region.iloc[-1]["sla_compliance_rate"]),
        "csat_sla_met": float(answered.loc[answered["sla_met"] == 1, "csat"].mean()),
        "csat_sla_missed": float(answered.loc[answered["sla_met"] == 0, "csat"].mean()),
    }


def results_markdown(star: StarSchema, quality: QualityResult) -> str:
    k = compute_kpis(star)
    i = insights(star)
    kpi_rows = pd.DataFrame([
        {"KPI": kpi.name, "Value": format_value(kpi.key, k[kpi.key]), "Owner": kpi.owner}
        for kpi in KPIS
    ])
    monthly = kpis_by(star, "month")
    monthly_view = pd.DataFrame({
        "Month": monthly["month"].astype(int),
        "Cases": monthly["case_volume"].map(lambda v: f"{v:,.0f}"),
        "SLA": monthly["sla_compliance_rate"].map(lambda v: f"{v:.1%}"),
        "Median arrival": monthly["median_arrival_min"].map(lambda v: f"{v:.0f} min"),
        "CSAT": monthly["csat_avg"].map(lambda v: f"{v:.2f}"),
        "App share": monthly["app_share"].map(lambda v: f"{v:.1%}"),
    })
    dq = quality.summary[["rule", "rows_flagged", "description"]]

    return f"""# Results

Generated by `python -m adl run` on {date.today().isoformat()}. All numbers come from the
synthetic data in this repository (fictional assistance service, calendar year 2025).

## Data quality

{len(quality.clean) + len(quality.quarantine):,} rows were loaded. {len(quality.quarantine):,} rows broke at least one
rule and were moved to `output/quarantine.csv` with the reason; {len(quality.clean):,} rows were kept.

{_table(dq)}

## KPIs (full year)

{_table(kpi_rows)}

## Findings

1. **Winter is the weak season for road service.** {i['sla_winter']:.1%} of road cases met the
   {SLA_ARRIVAL_MIN}-minute target in December to February, against {i['sla_rest']:.1%} in the rest of the
   year (median arrival {i['arrival_winter']:.0f} vs {i['arrival_rest']:.0f} min). Battery cases peak at the same
   time, so winter staffing and battery-only service vehicles are the first lever to look at.
2. **Regions differ a lot.** {i['weakest_region']} has the lowest SLA compliance ({i['weakest_region_sla']:.1%}),
   {i['strongest_region']} the highest ({i['strongest_region_sla']:.1%}). The slower regions are the more rural
   ones, so a single national target hides where members wait longest.
3. **Waiting time costs satisfaction.** Members whose help arrived within the target rated the service
   {i['csat_sla_met']:.2f}/5 on average, against {i['csat_sla_missed']:.2f}/5 when it did not.
4. **The digital intake works.** The app share rose from {i['app_before']:.1%} of cases before July to
   {i['app_after']:.1%} after the launch, and the average time until a dispatcher confirmed an app case fell
   from {i['app_contact_before']:.1f} to {i['app_contact_after']:.1f} minutes.

## Monthly view

{_table(monthly_view)}
"""


def use_cases_markdown(ranked: pd.DataFrame) -> str:
    view = ranked[["rank", "id", "title", "tool", "value", "effort", "data_ready", "risk", "score",
                   "recommendation"]].rename(columns={"data_ready": "data ready"})
    details = "\n".join(
        f"- **{row.id} {row.title}** ({row.process}, {row.users}): {row.success_measure}"
        for row in ranked.itertuples(index=False)
    )
    return f"""# Data & AI Use-Case Backlog

Each idea is rated 1-5 on value, effort, data readiness and risk.
Score = 2 x value + data readiness - effort - risk. Ideas with risk 5 (for example health data)
are marked "Review first" whatever their score: they need a data protection review before any test.

{_table(view)}

## How success is measured

Every use case gets a measurable success criterion before work starts:

{details}

## Next step for the top use case

UC01 (dispatcher handover summary) is tested with the intake test set in `evaluation/`.
See `docs/EVALUATION.md` for the results and the release gate.
"""


def evaluation_markdown(results: dict[str, tuple[dict, pd.DataFrame]]) -> str:
    rows = []
    for name, (m, _) in results.items():
        rows.append({
            "System": name,
            "Category accuracy": f"{m['category_accuracy']:.0%}",
            "Urgency accuracy": f"{m['urgency_accuracy']:.0%}",
            "Urgent cases found": f"{m['high_urgency_recall']:.0%}",
            "Fact coverage": f"{m['fact_coverage']:.0%}",
            "English summaries": f"{m['english_summaries']:.0%}",
            "Invented facts": m["unsupported_fact_cases"],
            "Passes gate": "yes" if m["passes_gate"] else "no (" + ", ".join(m["gate_failures"]) + ")",
        })
    sections = []
    for name, (m, detail) in results.items():
        errors = detail[~detail["category_ok"] | ~detail["urgency_ok"] | ~detail["english"]
                        | (detail["unsupported_facts"] != "") | (detail["fact_coverage"] < 1)]
        view = errors[["case_id", "expected_category", "category", "expected_urgency", "urgency",
                       "fact_coverage", "english", "unsupported_facts"]].copy()
        view["fact_coverage"] = view["fact_coverage"].map(lambda v: f"{v:.0%}")
        table = _table(view) if len(view) else "No errors."
        sections.append(f"### {name}: cases with at least one error\n\n{table}")
    return f"""# AI Assistant Evaluation: Case Intake

Test set: {len(next(iter(results.values()))[1])} member messages (English and German) in
`evaluation/test_cases.jsonl`, with the expected category, urgency and the facts every summary
must contain. The rules are in `evaluation/guidelines.md`.

Release gate: category accuracy >= 90%, every urgent case found, fact coverage >= 90%,
all summaries in English and no invented facts.

{_table(pd.DataFrame(rows))}

{chr(10).join(sections)}

## How to add another assistant

1. `python -m adl prompt` writes `prompts/copilot_batch_prompt.txt` and an empty `responses/template.csv`.
2. Paste the prompt into the assistant (for example Microsoft Copilot) and save its CSV answer as
   `responses/<name>.csv`.
3. Run `python -m adl evaluate`; every CSV in `responses/` is scored and this page is rewritten.
"""
